#!/usr/bin/env bash
# gen-service-companions.sh
#
# Generates the canonical per-service companion YAMLs (HPA + PDB +
# NetworkPolicy + ServiceMonitor + PrometheusRule + optional migrate
# Job) for every service in the platform tree. The output is split by
# tier (T1 / T2 / T3) per docs/architecture/DEPLOYMENT_ARCHITECTURE.md
# §Resource Limits.
#
# Usage: scripts/gen-service-companions.sh
# Output: services/<name>-policy.yaml per service (already includes HPA,
#         PDB, NetworkPolicy, ServiceMonitor, PrometheusRule, and
#         migrate Job where applicable — all 6 documents in one file).
set -euo pipefail
SERVICES_DIR="$(cd "$(dirname "$0")/.." && pwd)/services"

# tier: T1 / T2 / T3
# name: service name (kebab-case)
# port: app port
# actuator: actuator port
# priorityclass: PriorityClass name from infra/pdb-priority-config.yaml
# minreplicas/maxreplicas: HPA bounds
# cpu: CPU utilization target
# pdb_min: minAvailable for PDB (1 or 2)
# has_migrate: true if the service owns DB migrations
# migrate_args: args for the migrate Job (Spring Boot default)
# migrate_image_type: spring | go | python — controls migration tooling
# custom_metric: optional Pods metric name + target (e.g. "outbox_oldest_unpublished_seconds 5")
# alert_extras: optional extra alert rules (multi-line YAML snippet)

write_companion() {
  local name="$1" port="$2" actuator="$3" priorityclass="$4"
  local minreplicas="$5" maxreplicas="$6" cpu="$7" pdb_min="$8"
  local has_migrate="$9"
  shift 9
  local migrate_image_type="${1:-spring}" custom_metric="${2:-}" alert_extras="${3:-}"

  local file="${SERVICES_DIR}/${name}-policy.yaml"
  cat > "$file" <<EOF
# Per-service companion objects for ${name}.
#
# Auto-generated by scripts/gen-service-companions.sh.
# Tier: $(case "$priorityclass" in
  service-tier-1|ledger-service-priority|payment-service-priority|configuration-service-priority|api-gateway-priority) echo T1 ;;
  service-tier-2) echo T2 ;;
  service-tier-3) echo T3 ;;
  *) echo custom ;;
esac)
# App port ${port}, actuator port ${actuator}.
# PriorityClass: ${priorityclass}.
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/name: ${name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: ${minreplicas}
  maxReplicas: ${maxreplicas}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 25
          periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${cpu}
EOF

  if [[ -n "$custom_metric" ]]; then
    cat >> "$file" <<EOF
    - type: Pods
      pods:
        metric:
          name: ${custom_metric%% *}
        target:
          type: AverageValue
          averageValue: "${custom_metric##* }"
EOF
  fi

  cat >> "$file" <<EOF
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/name: ${name}
spec:
  minAvailable: ${pdb_min}
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
---
# NetworkPolicy — ${name} allows ingress only from api-gateway +
# admin-service + kubelet probes. Egress is covered by the
# platform-wide allow-services-to-* + allow-* policies.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/name: ${name}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ${name}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: api-gateway
      ports:
        - protocol: TCP
          port: ${port}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: admin-service
      ports:
        - protocol: TCP
          port: ${port}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/name: ${name}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
  endpoints:
    - port: actuator
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ${name}
  labels:
    app.kubernetes.io/name: ${name}
spec:
  groups:
    - name: ${name}.slo
      interval: 30s
      rules:
        - alert: ${name//-/_}SLOErrorRateHigh
          expr: |
            (
              sum(rate(http_server_requests_seconds_count{service="${name}",status=~"5.."}[1h]))
              /
              sum(rate(http_server_requests_seconds_count{service="${name}"}[1h]))
            ) > 0.005
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "${name} error rate > 0.5% (1h)"
            runbook: "https://wiki.trips-enjoy.com/runbooks/${name}"
        - alert: ${name//-/_}P99LatencyHigh
          expr: |
            histogram_quantile(0.99,
              sum by (route, le) (rate(http_server_requests_seconds_bucket{service="${name}"}[5m]))
            ) > 1.0
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "${name} p99 latency > 1s"
EOF

  if [[ -n "$alert_extras" ]]; then
    # alert_extras is expected to be a list of fully-indented rule
    # blocks (8 spaces) so they slot into the `rules:` list.
    echo "$alert_extras" >> "$file"
  fi

  if [[ "$has_migrate" == "true" ]]; then
    local migrate_cmd
    case "$migrate_image_type" in
      spring)
        migrate_cmd="migrate\n            - --spring.main.web-application-type=none"
        ;;
      go)
        migrate_cmd="migrate\n            - up"
        ;;
      python)
        migrate_cmd="alembic\n            - upgrade\n            - head"
        ;;
    esac
    cat >> "$file" <<EOF
---
# Helm-managed migration Job. Runs DB migrations before the
# Deployment rolls. Migrate image is the service's own image; the
# entrypoint picks the migrate subcommand.
apiVersion: batch/v1
kind: Job
metadata:
  name: ${name}-migrate
  labels:
    app.kubernetes.io/name: ${name}
    app.kubernetes.io/job: migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${name}
        app.kubernetes.io/job: migrate
    spec:
      restartPolicy: OnFailure
      serviceAccountName: ${name}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: migrate
          image: registry.trips-enjoy.com/${name}:dev-k8s
          imagePullPolicy: IfNotPresent
          args:
            - $(echo -e "$migrate_cmd")
          envFrom:
            - secretRef:
                name: ${name}-runtime
                optional: true
            - configMapRef:
                name: ${name}-config
                optional: true
          resources:
            requests: { cpu: 250m, memory: 512Mi }
            limits:   { cpu: "1",   memory: 1Gi  }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
EOF
  fi

  echo "wrote $file"
}

# Tier-1 services (already done: api-gateway, identity-service; ledger-service will be done by separate richer file)
# Remaining Tier-1: customer-service, geolocation-service, audit-service,
# payment-service, configuration-service, ledger-service.

# customer-service (T1)
write_companion "customer-service" 8089 9099 "service-tier-1" 3 8 70 2 \
  true "spring" "" ""

# geolocation-service (T1)
write_companion "geolocation-service" 8097 9107 "service-tier-1" 6 30 60 2 \
  true "go" "geocode_requests_per_second 200" ""

# audit-service (T1)
write_companion "audit-service" 8083 9093 "service-tier-1" 2 8 70 2 \
  true "spring" "audit_consumer_lag_seconds 30" \
  "        - alert: AuditServiceHashChainMismatch
          expr: increase(audit_hash_chain_mismatch_total[5m]) > 0
          for: 1m
          labels:
            severity: critical
            team: security-oncall
          annotations:
            summary: 'audit-service hash chain mismatch (TAMPER ALERT)'
            runbook: 'https://wiki.trips-enjoy.com/runbooks/audit-tamper'
            priority: P0"

# payment-service (T1)
write_companion "payment-service" 8098 9108 "payment-service-priority" 6 18 70 2 \
  true "spring" "payment_outbox_oldest_unpublished_seconds 5" ""

# configuration-service (T1)
write_companion "configuration-service" 8084 8081 "configuration-service-priority" 6 12 70 2 \
  true "spring" "configuration_outbox_oldest_unpublished_seconds 5" ""

# ledger-service (T1, financial) — handled separately because it has
# unique preStop + reconciliation CronJob. We still generate the
# companion file but mark it for the operator to add the CronJob later.
write_companion "ledger-service" 8099 9109 "ledger-service-priority" 6 18 70 2 \
  true "spring" "ledger_outbox_oldest_unpublished_seconds 5" \
  "        - alert: LedgerServicePostingLagHigh
          expr: increase(ledger_posting_lag_seconds[5m]) > 10
          for: 5m
          labels:
            severity: critical
            team: finance-oncall
          annotations:
            summary: 'ledger-service posting lag > 10s'
            priority: P0
        - alert: LedgerServiceReconciliationFailed
          expr: increase(ledger_reconciliation_failures_total[1h]) > 0
          for: 5m
          labels:
            severity: critical
            team: finance-oncall
          annotations:
            summary: 'ledger-service daily reconciliation FAILED'"

# Tier-2 services (10): notification, file, fraud-risk, trip, driver,
# courier, restaurant, food-order, pricing, search.
write_companion "notification-service" 8085 9095 "service-tier-2" 8 20 60 2 \
  true "spring" "notifications_in_flight 2000" ""

write_companion "file-service" 8101 9111 "service-tier-2" 6 12 60 2 \
  true "go" "files_uploads_per_second 50" ""

write_companion "fraud-risk-service" 8088 9098 "service-tier-2" 3 12 70 1 \
  true "python" "fraud_risk_queue_depth 100" ""

write_companion "trip-service" 8092 9102 "service-tier-2" 6 18 60 2 \
  true "spring" "" ""

write_companion "driver-service" 8091 9101 "service-tier-2" 6 18 60 2 \
  true "spring" "" ""

write_companion "courier-service" 8096 9106 "service-tier-2" 6 18 60 2 \
  true "spring" "" ""

write_companion "restaurant-service" 8094 9104 "service-tier-2" 3 12 70 1 \
  true "spring" "" ""

write_companion "food-order-service" 8095 9105 "service-tier-2" 6 18 60 2 \
  true "spring" "" ""

write_companion "pricing-service" 8093 9103 "service-tier-2" 6 12 70 2 \
  true "spring" "" ""

write_companion "search-service" 8090 9100 "service-tier-2" 3 12 70 1 \
  false ""

# Tier-3 services (2): chat, reporting.
write_companion "chat-service" 8100 9110 "service-tier-3" 2 6 70 1 \
  false ""

write_companion "reporting-service" 8087 9097 "service-tier-3" 2 6 70 1 \
  true "python" "" ""

echo "DONE — generated per-service companion files for 19 services"
echo "  (api-gateway and identity-service were hand-written)"
