spring:
  datasource:
    url: ${NOTIFICATION_SERVICE_DB_URL:jdbc:postgresql://0.0.0.0:5432/trips_enjoy?currentSchema=notification}
    username: ${NOTIFICATION_SERVICE_DB_USERNAME:postgres}
    password: ${NOTIFICATION_SERVICE_DB_PASSWORD:}
    hikari:
      connection-init-sql: 'CREATE SCHEMA IF NOT EXISTS notification;'
  data:
    redis:
      host: ${NOTIFICATION_SERVICE_REDIS_HOST:0.0.0.0}
      port: ${NOTIFICATION_SERVICE_REDIS_PORT:6379}
      password: ${NOTIFICATION_SERVICE_REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${NOTIFICATION_SERVICE_KAFKA_BOOTSTRAP_SERVERS:http://81.208.166.110:9092}

notification-service:
  keycloak:
    base-url: ${NOTIFICATION_SERVICE_KEYCLOAK_BASE_URL:http://0.0.0.0:8181}
    issuer-uri: ${NOTIFICATION_SERVICE_KEYCLOAK_ISSUER_URI:http://0.0.0.0:8181/realms/platform-services}
    jwks-uri: ${NOTIFICATION_SERVICE_KEYCLOAK_JWKS_URI:http://0.0.0.0:8181/realms/platform-services/protocol/openid-connect/certs}
    admin-realm: ${NOTIFICATION_SERVICE_KEYCLOAK_ADMIN_REALM:master}
    admin-client-id: ${NOTIFICATION_SERVICE_KEYCLOAK_ADMIN_CLIENT_ID:}
    admin-client-secret: ${NOTIFICATION_SERVICE_KEYCLOAK_ADMIN_CLIENT_SECRET:}
    admin-username: ${NOTIFICATION_SERVICE_KEYCLOAK_ADMIN_USERNAME:}
    admin-password: ${NOTIFICATION_SERVICE_KEYCLOAK_ADMIN_PASSWORD:}
