spring:
  datasource:
    url: ${RESTAURANT_SERVICE_DB_URL}
    username: ${RESTAURANT_SERVICE_DB_USERNAME}
    password: ${RESTAURANT_SERVICE_DB_PASSWORD}
    hikari:
      connection-init-sql: 'CREATE SCHEMA IF NOT EXISTS restaurant;'
  data:
    redis:
      host: ${RESTAURANT_SERVICE_REDIS_HOST}
      port: ${RESTAURANT_SERVICE_REDIS_PORT}
      password: ${RESTAURANT_SERVICE_REDIS_PASSWORD}
  kafka:
    bootstrap-servers: ${RESTAURANT_SERVICE_KAFKA_BOOTSTRAP_SERVERS}

restaurant-service:
  keycloak:
    base-url: ${RESTAURANT_SERVICE_KEYCLOAK_BASE_URL}
    issuer-uri: ${RESTAURANT_SERVICE_KEYCLOAK_ISSUER_URI}
    jwks-uri: ${RESTAURANT_SERVICE_KEYCLOAK_JWKS_URI}
    admin-realm: ${RESTAURANT_SERVICE_KEYCLOAK_ADMIN_REALM}
    admin-client-id: ${RESTAURANT_SERVICE_KEYCLOAK_ADMIN_CLIENT_ID}
    admin-client-secret: ${RESTAURANT_SERVICE_KEYCLOAK_ADMIN_CLIENT_SECRET}
    admin-username: ${RESTAURANT_SERVICE_KEYCLOAK_ADMIN_USERNAME}
    admin-password: ${RESTAURANT_SERVICE_KEYCLOAK_ADMIN_PASSWORD}
