spring:
  datasource:
    url: ${TRIP_SERVICE_DB_URL:jdbc:postgresql://0.0.0.0:5432/trips_enjoy?currentSchema=trip}
    username: ${TRIP_SERVICE_DB_USERNAME:postgres}
    password: ${TRIP_SERVICE_DB_PASSWORD:}
    hikari:
      connection-init-sql: 'CREATE SCHEMA IF NOT EXISTS trip;'
  data:
    redis:
      host: ${TRIP_SERVICE_REDIS_HOST:0.0.0.0}
      port: ${TRIP_SERVICE_REDIS_PORT:6379}
      password: ${TRIP_SERVICE_REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${TRIP_SERVICE_KAFKA_BOOTSTRAP_SERVERS:http://81.208.166.110:9092}

trip-service:
  keycloak:
    base-url: ${TRIP_SERVICE_KEYCLOAK_BASE_URL:http://0.0.0.0:8181}
    issuer-uri: ${TRIP_SERVICE_KEYCLOAK_ISSUER_URI:http://0.0.0.0:8181/realms/platform-services}
    jwks-uri: ${TRIP_SERVICE_KEYCLOAK_JWKS_URI:http://0.0.0.0:8181/realms/platform-services/protocol/openid-connect/certs}
    admin-realm: ${TRIP_SERVICE_KEYCLOAK_ADMIN_REALM:master}
    admin-client-id: ${TRIP_SERVICE_KEYCLOAK_ADMIN_CLIENT_ID:}
    admin-client-secret: ${TRIP_SERVICE_KEYCLOAK_ADMIN_CLIENT_SECRET:}
    admin-username: ${TRIP_SERVICE_KEYCLOAK_ADMIN_USERNAME:}
    admin-password: ${TRIP_SERVICE_KEYCLOAK_ADMIN_PASSWORD:}
