#!/usr/bin/env bash
# Mint a development HS256 JWT for local platform-engineering calls
# against the gateway. NOT for production — production tokens are
# RS256 and signed by Keycloak.
#
# Usage:
#   ./scripts/dev-jwt.sh [path/to/signing.pem] [subject] [role,role...]
#
# Examples:
#   ./scripts/dev-jwt.sh tmp/jwks/signing.pem platform.engineering admin

set -euo pipefail

key_path="${1:-./tmp/jwks/signing.pem}"
subject="${2:-platform.engineering}"
roles_csv="${3:-api_gateway.admin}"

# Build the header and payload (RS256 because the script signs with
# the RSA key generated by gen-jwks-fixture.sh). When the file is
# missing, fall back to HS256 with a deterministic dev secret.
if [[ -f "${key_path}" ]]; then
    header='{"alg":"RS256","typ":"JWT","kid":"api-gateway-dev"}'
    b64() { openssl base64 -A | tr -d '=' | tr '+/' '-_'; }
    sig=$(printf '%s' "$1" | openssl dgst -sha256 -sign "${key_path}" -binary | b64)
    alg="RS256"
else
    echo "signing key not found at ${key_path}; using HS256 with dev secret" >&2
    header='{"alg":"HS256","typ":"JWT"}'
    secret="dev-secret-do-not-use-in-prod"
    sig=$(printf '%s' "$1" | openssl dgst -sha256 -mac HMAC -macopt "key:${secret}" -binary \
        | openssl base64 -A | tr -d '=' | tr '+/' '-_')
    alg="HS256"
fi

now=$(date +%s)
exp=$((now + 3600))
roles_json=$(printf '"%s",' ${roles_csv//,/ } | sed 's/,$//')
payload=$(cat <<EOF
{"alg":"${alg}","sub":"${subject}","user_type":"service","tenant_id":"dev","roles":[${roles_json}],"iat":${now},"exp":${exp},"iss":"https://keycloak.cloud.habib.cloud/realms/platform-engineering","aud":["api-gateway"]}
EOF
)
b64() { openssl base64 -A | tr -d '=' | tr '+/' '-_'; }
header_b64=$(printf '%s' "${header}" | b64)
payload_b64=$(printf '%s' "${payload}" | b64)
unsigned="${header_b64}.${payload_b64}"

if [[ -f "${key_path}" ]]; then
    sig=$(printf '%s' "${unsigned}" | openssl dgst -sha256 -sign "${key_path}" -binary | b64)
fi

printf '%s.%s\n' "${unsigned}" "${sig}"
