FROM eclipse-temurin:21-jre-jammy
RUN useradd --system --create-home --uid 10001 identity
USER identity
WORKDIR /app
COPY build/libs/identity-service-0.0.1-SNAPSHOT.jar /app/app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/app/app.jar"]