spring.application.name=identity-service
server.port=8082
identity.public-url=${IDENTITY_PUBLIC_URL:http://localhost:8082}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
debug=true
springdoc.api-docs.path=/openapi.json
springdoc.swagger-ui.path=/docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.datasource.url=${IDENTITY_DB_URL:jdbc:postgresql://0.0.0.0:5432/trips_enjoy?currentSchema=identity}
spring.datasource.username=${IDENTITY_DB_USERNAME:postgres}
spring.datasource.password=${IDENTITY_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=identity
spring.flyway.schemas=identity
spring.flyway.default-schema=identity
spring.datasource.hikari.connection-init-sql="CREATE SCHEMA IF NOT EXISTS identity;"
spring.data.redis.host=${IDENTITY_REDIS_HOST:0.0.0.0}
spring.data.redis.port=${IDENTITY_REDIS_PORT:6379}
spring.data.redis.password=${IDENTITY_REDIS_PASSWORD:}
spring.kafka.bootstrap-servers=${IDENTITY_KAFKA_BOOTSTRAP_SERVERS:http://81.208.166.110:9092}
identity.keycloak.base-url=${IDENTITY_KEYCLOAK_BASE_URL:http://0.0.0.0:8181}
identity.keycloak.issuer-uri=${IDENTITY_KEYCLOAK_ISSUER_URI:http://0.0.0.0:8181/realms/platform-services}
identity.keycloak.jwks-uri=${IDENTITY_KEYCLOAK_JWKS_URI:http://0.0.0.0:8181/realms/platform-services/protocol/openid-connect/certs}
identity.keycloak.admin-username=${IDENTITY_KEYCLOAK_ADMIN_USERNAME:admin@inovoria.com}
identity.keycloak.admin-password=${IDENTITY_KEYCLOAK_ADMIN_PASSWORD:H@bib1998}
identity.keycloak.admin-realm=${IDENTITY_KEYCLOAK_ADMIN_REALM:platform-services}
identity.keycloak.admin-client-id=${IDENTITY_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
identity.keycloak.admin-client-secret=${IDENTITY_KEYCLOAK_ADMIN_CLIENT_SECRET:Yztlv8RpyyAKOxzOMzDOtoS2YkKfkG5r}
identity.outbox.publish-interval-ms=${IDENTITY_OUTBOX_PUBLISH_INTERVAL_MS:1000}
identity.session.denylist-ttl-seconds=${IDENTITY_SESSION_DENYLIST_TTL_SECONDS:86400}
identity.request-signing-secret=${IDENTITY_REQUEST_SIGNING_SECRET:}
identity.oidc.rewrite-base-url=${IDENTITY_OIDC_REWRITE_BASE_URL:}
identity.oidc.introspection-cache-ttl-seconds=${IDENTITY_OIDC_INTROSPECTION_CACHE_TTL_SECONDS:300}
identity.oidc.jwks-cache-ttl-seconds=${IDENTITY_OIDC_JWKS_CACHE_TTL_SECONDS:300}
identity.oidc.default-realm=${IDENTITY_OIDC_DEFAULT_REALM:platform-services}
identity.keycloak.seed.enabled=${IDENTITY_KEYCLOAK_SEED_ENABLED:true}
identity.keycloak.seed.admin-username=${IDENTITY_KEYCLOAK_ADMIN_USERNAME:admin@inovoria.com}
identity.keycloak.seed.admin-password=${IDENTITY_KEYCLOAK_ADMIN_PASSWORD:H@bib1998}
identity.keycloak.seed.super-admin-username=${IDENTITY_KEYCLOAK_SUPER_ADMIN_USERNAME:admin@trips-enjoy.com}
identity.keycloak.seed.super-admin-password=${IDENTITY_KEYCLOAK_SUPER_ADMIN_PASSWORD:H@bib1998}
identity.keycloak.seed.global-admin-enabled=${IDENTITY_KEYCLOAK_GLOBAL_ADMIN_ENABLED:true}
